fix(Theme): crashes on Android 7
FATAL EXCEPTION: main
Process: app.rvx.android.youtube, PID: 18048
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.rvx.android.youtube/com.google.android.apps.youtube.app.application.Shell_HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2701)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2765)
      at android.app.ActivityThread.-wrap12(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6262)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
      at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:423)
      at android.view.View.invalidateInternal(View.java:13692)
      at android.view.View.invalidate(View.java:13652)
      at android.view.View.setBackgroundDrawable(View.java:18392)
      at com.android.internal.policy.DecorView.setWindowBackground(DecorView.java:934)
      at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2710)
      at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2756)
      at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2169)
      at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:158)
      at android.app.Activity.performCreateCommon(Activity.java:6745)
      at android.app.Activity.performCreate(Activity.java:6752)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2654)
      ... 9 more